# =============================== Job Queue ===================================
[beanstalkd]
host = "0.0.0.0"
port = 11300
tube = "bell"

# ================================ Storage ====================================
[ssdb]
host = "0.0.0.0"
port = 8888

[ssdb.zset]  # to store datapoints
prefix = "bell."   # zset name prefix
expire = 432000  # 5day

[ssdb.zset.trending]  # to store values & anomalies trending
value = "bell.trending.value"
multi = "bell.trending.multi"

# ================================ Listener ===================================
[listener]
host = "0.0.0.0"
port = 8889

[listener.patterns]
# must pass at least one of the matches patterns and dont match any ignores
matches = ["*"]
ignores = ["statsd.*"]

# ================================ Analyzer ===================================
[analyzer]
strict = true
minSize = 50

[analyzer.filter]
offset = 0.01  # filter all points within `periodicity * offset`
periodicity = 86400  # 86400 = 24 * 60 * 60 = 1 day  (for all time series)

[analyzer.trending]
# for anomalies trending
factor = 0.3  # the bigger, the timeliness better. 0~1

# ================================ WebApp =====================================
[webapp]
port = 8989
root = ""   # set this if your webapp serves in a sub-directory.

# see `config/example.quickenters.json`, set to "" to disable it
quickenters = ""

# ================================ Alerter ====================================
[alerter]
host = "0.0.0.0"
port = 8789
modules = ["../alerters/hipchat.js"]

[alerter.hipchat]
roomId = 12345
token = "hipchat-api-token"
weburl = "http://bell.example.com"

since = 300  # 5min
threshold = 15
