# =============================== Job Queue ===================================
[beanstalkd]
host = "0.0.0.0"
port = 11300
tube = "bell"

# ================================ Storage ====================================
[ssdb]
host = "0.0.0.0"
port = 8888

prefix = "bell."   # zset/hash.. name prefix

[ssdb.zset]  # to store datapoints
expire = 432000  # 5day

# ================================ Listener ===================================
[listener]
host = "0.0.0.0"
port = 8889

[listener.prefixes]
matches = [""]
ignores = ["statsd."]

# ================================ Analyzer ===================================
[analyzer]
strict = true
minSize = 50

[analyzer.filter]
offset = 0.01  # filter all points within `periodicity * offset`
periodicity = 86400  # 86400 = 24 * 60 * 60 = 1 day  (for all time series)

[analyzer.trending]
# for anomalies trending
factor = 0.1  # the bigger, the timeliness better. 0~1

# ================================ WebApp =====================================
[webapp]
port = 8989
root = ""   # set this if your webapp serves in a sub-directory.

cacheInterval = 10  # cache interval for trendings

# see `config/example.quickenters.json`, set to "" to disable it
quickenters = ""

# see `config/example.timesteps.json`, set to "" to disable it, default: 10s
timesteps = ""


# ================================ Cleaner ====================================
[cleaner]
interval = 600   # clean interval, in seconds
threshold = 172800  # no data over 2 days, will be cleaned

[cleaner.prefixes]
matches = [""]
ignores = []

# ================================ Alerter ====================================
[alerter]
host = "0.0.0.0"
port = 8789
modules = ["../alerters/hipchat.js"]

[alerter.hipchat]
roomId = 12345
token = "hipchat-api-token"
weburl = "http://bell.example.com"

since = 300  # 5min
threshold = 15
