# =============================== Job Queue ===================================
[beanstalkd]
host = "0.0.0.0"
port = 11300
tube = "bell"

# ================================ Storage ====================================
[ssdb]
host = "0.0.0.0"
port = 8888
hash = "bell.allseries"   # to store all time series names

[ssdb.zset]  # to store datapoints
prefix = "bell."   # zset name prefix
expire = 432000  # 5day

# ================================ Listener ===================================
[listener]
port = 8889

[listener.patterns]
# must pass at least one of the matches patterns and dont match any ignores
matches = ["*"]
ignores = ["statsd.*"]

# ================================ Analyzer ===================================
[analyzer]
strict = true
minSize = 50

[analyzer.filter]
offset = 0.01  # filter all points within `periodicity * offset`
periodicity = 86400  # 86400 = 24 * 60 * 60 = 1 day  (for all time series)

# ================================ WebApp =====================================
[webapp]
port = 8989
root = ""   # set this if your webapp serves in a sub-directory.

# ================================ Hooks =======================================
[hooks]
enable = false
modules = ["../hook/hipchat"]

[hooks.hipchat]
roomId = 12345
token = "hipchat-api-token"
weburl = "http://bell.example.com"

since = 300  # 5min
threshold = 15
