# Node-Bell configuration. Docs: https://github.com/eleme/node-bell#configs

# =============================== Patterns ==================================
patterns = ""
interval = 10  # 10s

# =============================== Job Queue =================================
[beanstalkd]
host = "0.0.0.0"
port = 11300
tube = "bell"

# =============================== Storage ===================================
[ssdb]
host = "0.0.0.0"
port = 8888
prefix = "bell."
[ssdb.zset]
expire = 432000  # 5day

# =============================== Listener ==================================
[listener]
host = "0.0.0.0"
port = 8889

# =============================== Analyzer ==================================
[analyzer]
strict = true
minSize = 50

[analyzer.filter]
offset = 0.01
periodicity = 86400

[analyzer.trending]
factor = 0.1

# =============================== WebApp ====================================
[webapp]
port = 8989
root = ""

# =============================== Cleaner ===================================
[cleaner]
interval = 600
threshold = 172800

# =============================== Alerter ===================================
[alerter]
host = "0.0.0.0"
port = 8789
modules = ["../alerters/hipchat.js"]

[alerter.hipchat]
roomId = 12345
token = "hipchat-api-token"
weburl = "http://localhost:8989"

since = 300  # 5min
threshold = 15
