# =============================== Job Queue ===================================
[beanstalkd]
host = "0.0.0.0"
port = 11300
tube = "bell"

# ================================ Storage ====================================
[ssdb]
host = "0.0.0.0"
port = 8888
hash = "bell.allseries"   # to store all time series names

[ssdb.zset]  # to store datapoints
prefix = "bell."   # zset name prefix
cap = 43200  # 5 * 6 * 60 * 24 = 5 days

# ================================ Listener ===================================
[listener]
port = 2024

[listener.patterns]
# must pass at least one of the matches patterns and dont match any ignores
matches = ["*"]
ignores = ["statsd.*"]

# ================================ Analyzer ===================================
[analyzer]
strict = true  #  if strict mode
periodicity = 86400  # for all series, 86400 = 24 * 60 * 60 = 1 day
filterOffset = 0.01  # filter all points within `periodicity * offset`
minSeriesSize = 50  # analyze only if series's size is big than this value
severityTimeRecent = 3600  # calculate anomalous serverity in recent certain time

# ================================ WebApp =====================================
[webapp]
port = 8989
root = ""   # set this if your webapp serves in a sub-directory.

# ================================ Hooks =======================================
[hooks]
enable = false
modules = ["../hook/hipchat"]

[hooks.hipchat]
roomId = 12345
token = "your-hipchat-api-token"
weburl = "http://bell.example.com"

# notify only if at least <minCount> anomalies were found in last <recent> time
recent = 300  # 5min
minCount = 6
